package com.example.football6



var APP_PREFERENCES = "APP_PREFERENCES"
var RECORD_ALL_TIME_PENALTY = "RECORD_ALL_TIME_PENALTY"
var RECORD_TODAY_PENALTY = "RECORD_TODAY_PENALTY"
var RECORD_ALL_TIME_CORNERS = "RECORD_ALL_TIME_CORNERS"
var RECORD_TODAY_CORNERS = "RECORD_TODAY_CORNERS"
var RECORD_ALL_TIME_FREEKICK = "RECORD_ALL_TIME_FREEKICK"
var RECORD_TODAY_FREEKICK = "RECORD_TODAY_FREEKICK"
var ID = "ID"
lateinit var MAIN:MainActivity